# Generated by Django 4.2.4 on 2023-08-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='source_id',
            field=models.CharField(default='bbc-news', max_length=64),
            preserve_default=False,
        ),
    ]
