# Generated by Django 4.2.4 on 2023-09-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_default_profile_pic',
            field=models.BooleanField(default=True),
        ),
    ]
